##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Chicano Newspapers
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: A domestic spread of English and Spanish newspapers published at the height of the Chicano Movement
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "The collection consists of digitized Chicano periodicals produced across the United States during the 1960s and 1970s, including newspapers, newsletters, magazines, and zines that vary in format, layout, language (Spanish, English, and Spanglish), and production quality. As digital surrogates, primarily in JPG and some PDF formats, these items retain key descriptive features such as publication title, date, place of publication, and organizational affiliation, while also reflecting the technical inconsistencies of digitization across repositories. The primary users of this collection include scholars, students, community researchers, and digital humanists who seek to trace the geographic spread of Chicano activism, compare regional differences in political discourse, identify organizational networks, and access creative expressions embedded within periodicals. To support these uses, the metadata must enable multiple forms of discovery, including browsing by location (city and state), date and decade, publication title, organization, format, language, and thematic subject matter such as labor, education, and identity. Functionally, the metadata must allow users to map Chicano print culture beyond the American Southwest, retrieve items despite inconsistent naming conventions, distinguish between original print objects and digital surrogates, filter by media type and format, and clearly understand rights and reuse conditions. These requirements directly respond to the collection’s organizing challenges, particularly the instability of terms such as “Chicano,” “Latino,” and “Hispanic,” and the uneven quality and structure of existing metadata across repositories, necessitating a schema that is both standardized and flexible enough to accommodate ambiguity while still supporting meaningful discovery and analysis."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Michelle Garcia

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: Chicano-Metadata

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
